name: Deploy Function App Infra

on: 
  workflow_dispatch

permissions: 
  id-token: write
  contents: read

jobs:
  deploy_Function_infra:

    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
            terraform_version: 1.3.7
    
      - name: Terraform Init
        working-directory: ./terraform
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ secrets.AZURE_RESOURCE_GROUP }}" \
            -backend-config="storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT }}" \
            -backend-config="container_name=${{ secrets.AZURE_CONTAINER }}" \
            -backend-config="key=function.tfstate"

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan 
            # -backend-config="resource_group_name=${{ secrets.AZURE_RESOURCE_GROUP }}" \
            # -backend-config="storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT }}" \
            # -backend-config="container_name=${{ secrets.AZURE_CONTAINER }}" \
            # -backend-config="key=function.tfstate"

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve
            # -backend-config="resource_group_name=${{ secrets.AZURE_RESOURCE_GROUP }}" \
            # -backend-config="storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT }}" \
            # -backend-config="container_name=${{ secrets.AZURE_CONTAINER }}" \
            # -backend-config="key=function.tfstate"

      - name: Wait for 10 minutes
        run: |
              echo "Waiting for 10 minutes..."
              sleep 600  # 600 seconds = 10 minutes

      - name: Terraform Destroy
        working-directory: ./terraform
        run: terraform destroy  -auto-approve
 